WIP: feat: completed the initial version design for the moments feature.
halo-sigs/plugin-moments pull request #2
Opened 2023-03-17 07:04 UTC by LIlGG

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
瞬间插件初版功能设计。
Console 端：
1. 增加了“瞬间”管理页面。用户将可以通过 Console 创建瞬间。
2. 支持瞬间内容添加图片，视频。
3. 支持使用富文本编辑器。

主题端：
1. 新增了 `/moments` 及 '/moments/page/{page}' 路由，需使用 `moments.html` 页面，分页数量在插件设置中进行修改。
2. 增加了 `momentFinder`。

#### how to test it?
1. 测试 Console 端瞬间基本逻辑是否正确。包括
    a. 新增一个瞬间内容，查看是否能够刷新列表且内容是否正确，图片或视频是否存在，可见性是否支持。
    b. 双击已经存在的瞬间内容，查看是否能够修改，且修改后的数据是否正确。
    c. 删除一个瞬间内容，查看能否被成功删除。
    d. 使用搜索框，查看对应的瞬间内容能否被搜索到。
    e. 查看分页数据是否符合逻辑。
2. 测试主题端 `moments.html` 是否能够存在 `moments` 数据，以及分页是否正常。
3. 测试主题端 `momentFinder` 是否能够正确读取到数据，分页是否正常。

#### Does this PR introduce a user-facing change?

```release-note
增加瞬间插件，为主题端提供 `/moments` 路由
```

基于 PR https://github.com/halo-sigs/plugin-moments/pull/1 完成，因此目标 PR 可以进行关闭。

2023-03-21 07:19 UTC, ruibaby commented
实际测试发现以下问题：

**1. 筛选框 UI 与 Core 不统一**

<img width="835" alt="image" src="https://user-images.githubusercontent.com/21301288/226539516-ad653c6e-a98d-4179-ab3e-b4ba755ca17b.png">

**2. 双击已存在的 Moment 进入编辑之后，无法再双击选中文字**

![2023-03-21 15 16 56](https://user-images.githubusercontent.com/21301288/226540000-e9435947-219d-495b-a6c8-04cc5877f565.gif)

**3. 图片长宽比不统一，可以使用 Tailwindcss 的 aspect-ratio 插件**

<img width="652" alt="image" src="https://user-images.githubusercontent.com/21301288/226540051-bea1185e-4e5f-4824-b73d-6fab640dbe22.png">

2023-03-23 03:19 UTC, LIlGG commented
> 实际测试发现以下问题：
> 
> **1. 筛选框 UI 与 Core 不统一**
> 

已经对筛选框的 UI 进行优化，与 Core 保持一致。但 rangeTime 比较特殊，无法完全保持一致。
![image](https://user-images.githubusercontent.com/31335418/227088746-94ccb195-6dfc-4c4d-a4ce-58bb3b8ac015.png)


> **2. 双击已存在的 Moment 进入编辑之后，无法再双击选中文字**
> 

移除了双击取消编辑的情况。最新情况下，双击可以进入编辑，但无法进行取消编辑，需要点击右下角取消按钮。
![image](https://user-images.githubusercontent.com/31335418/227089087-dd982123-e15f-413f-9dde-82cd57f4c3e5.png)


> 
> **3. 图片长宽比不统一，可以使用 Tailwindcss 的 aspect-ratio 插件**
> 

已经使用 aspect-ratio 保持图片纵横比

2023-04-01 03:21 UTC, ruibaby requested changes
@LIlGG 这里有一点修改建议，有空请检查一下。

2023-04-01 03:21 UTC, ruibaby commented on README.md
> +## 使用方式
建议把使用方式放在最前面。如果可以，最好配个截图。

2023-04-01 03:21 UTC, ruibaby commented on build.gradle
> +    compileOnly 'org.springframework.boot:spring-boot-starter-security'
为什么要加 security 的依赖？

2023-04-01 03:21 UTC, ruibaby commented on console/src/styles/index.css
> -.title {
能否使用 sass 整理一下？

2023-04-01 03:21 UTC, ruibaby commented on console/src/utils/date.ts
> +import dayjs from "dayjs";
建议加上注释：// 后续期望 Console 在 shared 包中提供统一的日期时间方法。

2023-04-01 03:21 UTC, ruibaby commented on console/src/components/EditorBubbleMenu.vue
> +<script lang="ts" setup>
建议加上注释：// TODO: 后续期望 `@halo-dev/richtext-editor` 提供。

2023-04-01 03:21 UTC, ruibaby commented on console/src/components/EditorLinkBubbleMenuItems.vue
> +<script lang="ts" setup>
建议加上注释：// TODO: 后续期望 `@halo-dev/richtext-editor` 提供。

2023-04-01 03:21 UTC, ruibaby commented on console/src/components/MomentEdit.vue
> +const isEditorEmpty = ref<boolean>(true);
我们不可以用 `formState.spec.content.raw` 的值判断编辑器是否为空吗？

2023-04-01 03:21 UTC, ruibaby commented on console/src/components/MomentEdit.vue
> +const insertMoment = async () => {
`createMoment` may be better

2023-04-01 03:21 UTC, ruibaby commented on console/src/components/MomentEdit.vue
> +const MediumWhitelist: Map<string, MomentMediaTypeEnum> = new Map([
并不是所有以 image/ 开头的类型都可以在网页上显示，是否可以穷举一下支持的图片，然后直接在下面使用 includes 来匹配？

比如：

```ts
const imageTypes = ["image/jpeg", "image/jpg", "image/png", "image/gif", "image/webp", "image/svg+xml"]

const isImage = imageTypes.include(media.type)
```

2023-04-01 03:21 UTC, ruibaby commented on console/src/components/MomentEdit.vue
> +const removeMedium = (medium: MomentMedia) => {
注意一下命名，最好全局检查一下，这里应该是单个媒体，所以应该是 media。

2023-04-01 03:21 UTC, ruibaby commented on console/src/components/MomentEdit.vue
> +  let index: number | undefined = formMedium.indexOf(medium);
Array 的 indexOf 的返回类型只会是 number

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/21301288/229263193-1b0d481c-d16e-4078-b702-972b81d22971.png">

2023-04-01 03:21 UTC, ruibaby commented on console/src/components/MomentEdit.vue
> +  if (index != -1) {
```suggestion
  if (index > -1) {
```

2023-04-01 03:21 UTC, ruibaby commented on console/src/components/MomentPreview.vue
> +const removeMoment = () => {
```suggestion
const deleteMoment = () => {
```

2023-04-01 04:34 UTC, LIlGG commented on console/vite.config.ts
> +};
> 此外，Vite 默认包含 MODE 的环境变量，不需要再手动指定 `--mode dev`，请参考：https://vitejs.dev/guide/env-and-mode.html#modes

默认情况下确实是包含了 MODE 的环境变量，但插件无论是 dev 还是 build 都最终使用了 build，因此需要指定 mode。不过也仅需要指定 dev 的即可， build 的确实是多余了。

2023-04-01 04:41 UTC, ruibaby commented on console/vite.config.ts
> +};
那你在 script 指定为 `--mode development` 即可，不用自己加一个 dev

2023-04-01 04:45 UTC, LIlGG commented on console/src/components/MomentEdit.vue
> +const isEditorEmpty = ref<boolean>(true);
> 我们不可以用 `formState.spec.content.raw` 的值判断编辑器是否为空吗？

不建议使用 `formState.spec.content.raw` 判断。编辑器输入之后，即便删除掉文本还是会存在 `p` 标签， raw 内也不会为空。因此使用编辑器提供的判断为空方法最为恰当。

2023-04-01 04:46 UTC, LIlGG commented on console/vite.config.ts
> +};
> 那你在 script 指定为 `--mode development` 即可，不用自己加一个 dev

了解

2023-04-01 04:48 UTC, LIlGG commented on build.gradle
> +    compileOnly 'org.springframework.boot:spring-boot-starter-security'
> 为什么要加 security 的依赖？

俺也不知道。。可能是之前模板上的吧，没注意。

2023-04-01 04:49 UTC, LIlGG commented on console/src/styles/index.css
> -.title {
> 能否使用 sass 整理一下？

真的要用 sass 吗？目前整个插件项目我没有用到 sass 的地方。。

2023-04-01 06:57 UTC, LIlGG commented on console/src/components/MomentEdit.vue
> +const MediumWhitelist: Map<string, MomentMediaTypeEnum> = new Map([
> 并不是所有以 image/ 开头的类型都可以在网页上显示，是否可以穷举一下支持的图片，然后直接在下面使用 includes 来匹配？

确实应该限制可显示的类型，但由于目前没有标准化的支持列表，而且根据每个用户代理不同，可能支持的列表也不同。所以我建议仅提供一些常见的图像格式。

2023-04-01 07:09 UTC, ruibaby commented on console/src/components/MomentEdit.vue
> +const MediumWhitelist: Map<string, MomentMediaTypeEnum> = new Map([
我的意思就是我们来维护哪些格式可以显示，如果后续有其他需求可以再添加。

2023-04-01 07:15 UTC, ruibaby commented on console/src/styles/index.css
> -.title {
取决于你，我认为你目前的 index.css 如果用 scss 可能结构更清晰，并且安装 sass 也非常简单：

```bash
pnpm install sass -D
```

```css
.moments-content .halo-moment-editor .editor-header {
  height: 48px;
}

.moments-content .halo-moment-editor .editor-content {
  height: 100%;
  width: 100%;
}

.moments-content .halo-moment-editor .editor-content .ProseMirror {
  min-height: 7.25rem;
  overflow: auto;
  outline: none !important;
}
```

->

```scss
.moments-content {
  .halo-moment-editor {
    .editor-header {
      height: 48px;
    }
    .editor-content {
      height: 100%;
      width: 100%;
      .ProseMirror {
        min-height: 7.25rem;
        overflow: auto;
        outline: none !important;
      }
    }
  }
}
```

2023-04-01 07:38 UTC, LIlGG commented on build.gradle
> +    compileOnly 'org.springframework.boot:spring-boot-starter-security'
> 为什么要加 security 的依赖？

看了一下，这里增加依赖是 moments 需要保存当前用户的信息，因此 compile 了 security。

2023-04-01 07:48 UTC, LIlGG commented on console/src/components/MomentEdit.vue
> +  return data;
> return data 的作用？

确实没有作用，之前留着只是想着后面会不会用到，已删除。

2023-04-01 07:49 UTC, LIlGG commented on README.md
> +## 使用方式
> 建议把使用方式放在最前面。如果可以，最好配个截图。

使用方式放到前面了，但不知道配什么图。QAQ

2023-04-01 09:18 UTC, ruibaby commented on README.md
> +## 使用方式
那就先不配

2023-04-01 09:47 UTC, ruibaby approved these changes
/approve

2023-04-03 09:59 UTC, ruibaby approved these changes
/approve

2023-04-03 11:47 UTC, guqing reviewed
/lgtm

2023-04-03 11:48 UTC, merged