docs: supplement tag documentation
halo-sigs/plugin-moments pull request #36
Opened 2023-07-10 04:18 UTC by LIlGG

补充标签文档

```release-note
None
```

2023-07-10 04:23 UTC, guqing reviewed
/lgtm

2023-07-10 07:10 UTC, JohnNiang requested changes

2023-07-10 07:10 UTC, JohnNiang commented on README.md
> +    "momentCount": "string",                    // 标签名称
momentCount 也是标签名称么？

2023-07-10 07:19 UTC, LIlGG commented on README.md
> +    "momentCount": "string",                    // 标签名称
> momentCount 也是标签名称么？

已修改

2023-07-20 02:48 UTC, ruibaby approved these changes
/lgtm

2023-07-20 02:50 UTC, merged